@API_TOKEN_LOCAL = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTJkYmRkMTEwNjE5ZDMxMTg0NDM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU1NTAzNTgxLCJleHAiOjE3NTU3NjI3ODF9.sIgI6YSHusZgWl9_EJglwiwF120Z4uRY8BSM3TK8Ihc
@API_BASE_URL_LOCAL = http://localhost:8000/api/v1


# kyc list
GET  {{API_BASE_URL_LOCAL}}/admin/kyc/kyc-list
Authorization:{{API_TOKEN_LOCAL}}



