@API_TOKEN_LOCAL = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTJmNTJmZDExMzZkMzFiNmYzYzM5NCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTUxMDA2MywiZXhwIjoxNzU1NzY5MjYzfQ.dFeju_DJMZJzkC6fR1dzmjtkl9DkFXuBcfFI0lDy0zI
@API_BASE_URL_LOCAL = http://localhost:8000/api/v1


# kyc list
GET  {{API_BASE_URL_LOCAL}}/admin/kyc/kyc-list
Authorization:{{API_TOKEN_LOCAL}}

 # kyc detiail
GET  {{API_BASE_URL_LOCAL}}/admin/kyc/kyc-details/68a2ddc14f7b1476e5888344
Authorization:{{API_TOKEN_LOCAL}}



