@API_TOKEN_LOCAL = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWQ3MWRmNmEyZjYwNTQwMDNkNDllMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU1MTQ4NzY3LCJleHAiOjE3NTU0MDc5Njd9.vGC-WwJzndjdxaqRczQ0CzBsX-d_S2aqdpaxxLQvzn4
@API_BASE_URL_LOCAL = http://localhost:8000/api/v1



# My Profile
GET {{API_BASE_URL_LOCAL}}/user/my-profile
Authorization:{{API_TOKEN_LOCAL}}

### Register User
POST {{API_BASE_URL_LOCAL}}/user/register
Content-Type: application/json

{
   "firstName" :"Mohammed",
   "lastName" :"Shahid",
   "email" :"test@gmail.com",
   "gender" :"male",
   "phoneNumber" :"+971504536784",
   "password" :"Test@123",
   "confirmPassword" :"Test@123"
}



